language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
env:
  - DOCUTILS=0.11
  - DOCUTILS=0.12
install:
  - pip install -U pip
  - pip install docutils==$DOCUTILS
  - pip install -r test-reqs.txt
before_script: flake8
script: make test
