language: python
sudo: false
dist: trusty
cache: pip

env:
  global:
    - PYTHONFAULTHANDLER=x
    - PYTHONWARNINGS=all
    - SKIP_LATEX_BUILD=1

matrix:
  include:
    - python: 'pypy'
      env: TOXENV=pypy
    - python: '2.7'
      env: TOXENV=du13
    - python: '3.4'
      env: TOXENV=py34
    - python: '3.5'
      env: TOXENV=py35
    - python: '3.6'
      env: TOXENV=py36
    - python: 'nightly'
      env: TOXENV=py37
    - python: '3.6'
      env: TOXENV=mypy
    - python: '2.7'
      env: TOXENV=flake8

addons:
  apt:
    packages:
      - graphviz
      - imagemagick

install:
  - pip install -U tox

script:
  - tox -- -v
