name: CI

on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-18.04
    name: Python ${{ matrix.python }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - python: "3.6"
          docutils: du14
        - python: "3.7"
          docutils: du15
        - python: "3.8"
          docutils: du16
        - python: "3.9"
          docutils: du17
        - python: "3.10"
          docutils: du18
        - python: "3.11-dev"
          docutils: py311

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v3
      if: "!endsWith(matrix.python, '-dev')"
      with:
        python-version: ${{ matrix.python }}
    - name: Set up Python ${{ matrix.python }} (deadsnakes)
      uses: deadsnakes/action@v2.0.1
      if: "endsWith(matrix.python, '-dev')"
      with:
        python-version: ${{ matrix.python }}
    - name: Check Python version
      run: python --version
    - name: Install graphviz
      run: sudo apt-get install graphviz
    - name: Install dependencies
      run: python -m pip install -U pip tox
    - name: Run Tox
      run: tox -e ${{ matrix.docutils }} -- -vv

  windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3
    - name: Install dependencies
      run:  python -m pip install -U pip tox
    - name: Run Tox
      run:  tox -e py -- -vv

  coverage:
    # only run on pushes to branches in the sphinx-doc/sphinx repo
    if: github.repository_owner == 'sphinx-doc' && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3
      uses: actions/setup-python@v3
      with:
        python-version: 3

    - name: Check Python version
      run: python --version

    - name: Install graphviz
      run: sudo apt-get install graphviz

    - name: Install dependencies
      run: python -m pip install -U pip tox pytest-cov

    - name: Run Tox
      run: tox --sitepackages -e py -- -vv
      env:
        PYTEST_ADDOPTS: "--cov ./ --cov-append --cov-config setup.cfg"

    - name: codecov
      uses: codecov/codecov-action@v3
